### PR TITLE
Specs/grains observation

### LINKED ISSUE #1539: Magic code check in RetryFailedPartitionJob
I don't understand this `SuccessfulSteps` check:
```csharp
 /// <inheritdoc/>
  public override async Task OnCompleted()
    {
        if (State.Progress.SuccessfulSteps == 1)
        {
            var observer = GrainFactory.GetGrain<IObserver>(Request.ObserverKey);
            await observer.FailedPartitionRecovered(Request.Key);
        }
    }
```

### LINKED ISSUE #1543: ReplayObserverPartition calls Observer.PartitionReplayed which throws exception
`public Task PartitionReplayed(Key partition) => throw new NotImplementedException();`

### PR DESCRIPTION
**Pull request by woksin**
## Summary

In the process of adding specs to the Observation system many smaller issues were discovered and fixed. Along with general code cleanup and refactoring.

### Added

- More Logging
- Replaying and CatchingUp partitions to ObserverState

### Changed

- Various code in the kernel to make it cleaner and more robust

### Fixed

- `JobStep` did not save state when paused
- Catching up failing or replaying partitions
- Improved resilience around Observers and Jobs
- Fixes #1543
- Fixes #1539

### Removed

- `Handled` from ObserverState counting the number of handled events. This can be done differently in the future

### CODE REVIEW

**Comment by woksin** [comment]
Follow up tasks from this is to go over the job system with specs and then move over to through integration testing

File: Source/Kernel/Concepts/Observation/FailedPartitions.cs [hunk 1]
```diff
@@ -12,46 +13,49 @@ namespace Cratis.Chronicle.Concepts.Observation;
...
-        set => _partitions = new(value);
+        get => _partitions.Values;
+        set
+        {
+            _partitions.Clear();
+            foreach (var failedPartition in value)
+            {
+                var key = failedPartition.Partition;
+                _partitions.Add(key, failedPartition);
+            }
```
Comment (einari) [inline Source/Kernel/Concepts/Observation/FailedPartitions.cs:31]: This could be with LINQ:

```suggestion
            _partitions = failedPartitions.ToDictionary(_ => _.Partition, _ => _);
```

File: Source/Kernel/Grains/Observation/Jobs/HandleEventsForPartition.cs [hunk 2]
```diff
@@ -21,108 +22,122 @@ namespace Cratis.Chronicle.Grains.Observation.Jobs;
...
     IObserverSubscriber? _subscriber;
 
     /// <inheritdoc/>
     public override Task Prepare(HandleEventsForPartitionArguments request)
     {
-        var eventSourceId = (EventSourceId)(request.Partition.Value.ToString() ?? string.Empty);
+        using var scope = logger.BeginObserverScope(request.ObserverKey, State.Id.JobId, State.Id.JobStepId);
+        logger.Preparing(request.Partition, request.StartEventSequenceNumber, request.EndEventSequenceNumber);
         _observer = GrainFactory.GetGrain<IObserver>(request.ObserverKey);
+        _eventSourceId = request.Partition.Value?.ToString() ?? EventSourceId.Unspecified;
```
Comment (einari) [inline Source/Kernel/Grains/Observation/Jobs/HandleEventsForPartition.cs:45]: `Key` has an override for `.ToString()`. The `Value` within `Key` is not nullable, so I think this can be simplified to:

```suggestion
        _eventSourceId = request.Partition.ToString();
```

**Review by einari — COMMENTED** [review]
Great work!  Much needed refactorings!

**Review by einari — APPROVED** [review]
Approving the rest of the PR, as long as it builds with the proposed changes
